### ISSUE TITLE
Insufficient privileges Error

### ISSUE THREAD

**Issue by iliatcymbal** [bellingard/sonar-scanner-npm#10]
Hi.
I'm trying to run sonar for my project, but got this:

ERROR: Error during SonarQube Scanner execution
ERROR: Insufficient privileges

[http://joxi.ru/52aYO83I4x03R2](url)

Maybe it's due to typescript files?

**Comment by bellingard** [comment]
Can you copy-paste how you configure the analysis?

**Comment by iliatcymbal** [comment]
just:

```
var sonarqubeScanner = require('sonarqube-scanner');

sonarqubeScanner({
  serverUrl : "https://sonarqube.com",
  token : "c82c012a2ec6b0b8809d001759a3a59cd8eb9d41",
  options : {}
}, console.log);
```

**Comment by bellingard** [comment]
OK, you have to pass the "sonar.organization" parameter in the "options" map. This is why you get this error.

For instance, based on your GitHub login, if you want to push to your personal org on SonarCloud, this would be:
```
var sonarqubeScanner = require('sonarqube-scanner');

sonarqubeScanner({
  serverUrl : "https://sonarqube.com",
  token : "...",
  options : {
    "sonar.organization": "iliatcymbal-github"
  }
}, console.log);
```

Can you tell me if that works?

**Comment by iliatcymbal** [comment]
oh, that worksfor me! Thank you a lot.

**Comment by bellingard** [comment]
OK, thanks for the info.
I will improve the documentation, and probably add a dedicated option to specify the organization.

Thanks for your feedback!
