### ISSUE TITLE
Scanner unable to parse Null Propogation Operator

### ISSUE THREAD

**Issue by Fallibilist** [bellingard/sonar-scanner-npm#103]
The null propagation operator has full support in Node v14+ which is installed on the agent.
Using SonarScanner v4.3.0.2102 I receive the error that the files are unable to be parsed on those lines which contain the ?. syntax. 

Has anyone else run into this issue and been able to resolve it? Older versions of node exist on the agent, I'm using "nvm use" to set the node version. Do I need to specify the node versions elsewhere for the scanner?

Thanks!

**Comment by gabssnake** [comment]
Hey @Fallibilist is this still an issue for you? Did you find any workaround?

**Comment by gabssnake** [comment]
Closing this as stale. Please reopen if needed.
