### ISSUE TITLE
Suggestion - to add to your README

### ISSUE THREAD

**Issue by inspiraller** [bellingard/sonar-scanner-npm#104]
# How to run, for local installation in package.json (to automatically pick up sonar-project.properties)- 
```javascript
  "scripts": {
    "sonar-scanner": "node node_modules/sonarqube-scanner/dist/bin/sonar-scanner"
  }
```
# Run from npm
npm run sonar-scanner

**Comment by gabssnake** [comment]
Hey @inspiraller, would you want to do s small PR with this?

**Comment by gabssnake** [comment]
Hi @oliviernt,

I created a list of potential improvements and mentioned this:
* #165

I'll close this issue for now. Feel free to reopen if you have more information or if you want to try the PR.
