### ISSUE TITLE
Link for fix in FAQ does not work

### ISSUE THREAD

**Issue by MaxChal** [bellingard/sonar-scanner-npm#105]
The link to show how to fix java manually is not working.

FAQ question:
In my Docker container, the scanner fails with ".../jre/bin/java: not found", how do I solve this?

Broken link:
https://ghost.kontena.io/docker-for-mac-glibc-issues/

**Comment by gabssnake** [comment]
Hey @MaxChal, did you find a workaround for this?

**Comment by gabssnake** [comment]
This should be fixed with https://github.com/bellingard/sonar-scanner-npm/pull/134.
Closing for now.
