### ISSUE TITLE
Usage with grunt?

### ISSUE THREAD

**Issue by Jaff** [bellingard/sonar-scanner-npm#109]
I've inherited a project using grunt, and wish to add your scanner. I had no success with the https://github.com/skhatri/grunt-sonar-runner (4 years old!) so I thought I could use yours. Any suggestions for configuration setup?

**Comment by Jaff** [comment]
Nobody has used this with grunt?

**Comment by egore** [comment]
I've been using it like this in Gruntfile.js:

    var sonar = require('sonarqube-scanner');

    module.exports = function (grunt) {
        grunt.initConfig({...});

        grunt.registerTask('sonar', function() {
            sonar({
                serverUrl: '...',
                options: {...}
            });
        });
    };

Afterwards you call it via "grunt sonar"

**Comment by gabssnake** [comment]
Hey guys, this seems to be solved for now. Feel free to reopen if anything new comes up.
