### ISSUE TITLE
Add dedicated "organization" parameter

### ISSUE THREAD

**Issue by bellingard** [bellingard/sonar-scanner-npm#11]
For users on SonarCloud, the organization must be specified - which is not that obvious when reading the doc (see #10).

So:
* Let's add an "organization" parameter
* Let's better document this.

**Comment by gabssnake** [comment]
Still relevant as today.

**Comment by gabssnake** [comment]
I created a list of potential improvements and mentioned this topic:
* #165

I'll close this issue for now. Feel free to reopen if you want to create a PR ;)
