### ISSUE TITLE
Sensors unable to analyze typescript code in src folder

### ISSUE THREAD

**Issue by BoucheeMalcolm** [bellingard/sonar-scanner-npm#117]
The directory structure is basically this after running npm build

dist -> projectname -> artifacts in javascript
e2e -> miscellaneous angular files
src -> various typescript artifacts that developer works on

When running sonar cli I've tried specifying src, dist, or the entire file directory via ' ./ '. When specifying dist, dist was scanned with SensorJS. When specifying src (which contains the typescript,javascript the dev is building), SensorJS isn't triggered and nothing is scanned. When specifying the entire directory, dist and e2e folders are scanned. 

Dist folder contains the code that is running, but the src folder contains what a developer would modify to pass quality gate. 

The only difference I see is that the src folder contains no .js files, thus it never gets scanned. Shouldn't this work for both ts and js files?

I want to avoid using the sonar npm dependency, because the developer skillset is limited and I wanted our CI/CD pipelines to manage the scans via the CLI tool.

Thanks,

**Comment by gabssnake** [comment]
Closing this as stale. Feel free to reopen in new information comes up.
