### ISSUE TITLE
Unable to fetch binaries from mirror with authentication

### ISSUE THREAD

**Issue by hitdatoc** [bellingard/sonar-scanner-npm#118]
We are trying to fetch sonarqube binaries from our own internal server, but it requires basic authentication. 
However using the http://username:password@domain.com URL format does not work and returns the ff. error:

` throw new Error('Basic authentication must be done with the `auth` option');`

Is there a way in order to configure it to use basic auth?

Thank you very much in advance!

**Comment by gabssnake** [comment]
Hey @hitdatoc, did you find a workaround for this?

**Comment by gabssnake** [comment]
Hi @oliviernt,

I created a list of potential improvements and mentioned the problem you are/were experiencing:
* #165

I'll close this issue for now. Feel free to reopen if you have more information.
