### ISSUE TITLE
cannot install using nodejs 15.14.0

### ISSUE THREAD

**Issue by gabricar** [bellingard/sonar-scanner-npm#120]
$ docker run -it --entrypoint sh node:15.14.0-alpine3.13

/ # npm install sonarqube-scanner
npm ERR! Tracker "idealTree" already exists

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-04-16T17_55_55_500Z-debug.log
/ # cat /root/.npm/_logs/2021-04-16T17_55_55_500Z-debug.log
0 verbose cli [
0 verbose cli   '/usr/local/bin/node',
0 verbose cli   '/usr/local/bin/npm',
0 verbose cli   'install',
0 verbose cli   'sonarqube-scanner'
0 verbose cli ]
1 info using npm@7.10.0
2 info using node@v15.14.0
3 timing npm:load:whichnode Completed in 2ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 0ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/.npmrc Completed in 0ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:/root/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setEnvs Completed in 1ms
17 timing config:load Completed in 6ms
18 timing npm:load:configload Completed in 6ms
19 timing npm:load:setTitle Completed in 0ms
20 timing npm:load:setupLog Completed in 1ms
21 timing npm:load:cleanupLog Completed in 2ms
22 timing npm:load:configScope Completed in 0ms
23 timing npm:load:projectScope Completed in 0ms
24 timing npm:load Completed in 12ms
25 timing config:load:flatten Completed in 3ms
26 timing arborist:ctor Completed in 1ms
27 timing arborist:ctor Completed in 0ms
28 timing idealTree:init Completed in 14ms
29 timing idealTree:userRequests Completed in 2ms
30 silly idealTree buildDeps
31 timing idealTree Completed in 18ms
32 timing command:install Completed in 29ms
33 verbose stack Error: Tracker "idealTree" already exists
33 verbose stack     at Arborist.[_onError] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/tracker.js:101:11)
33 verbose stack     at Arborist.addTracker (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/tracker.js:28:21)
33 verbose stack     at Arborist.[buildDeps] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:745:10)
33 verbose stack     at Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:217:29)
33 verbose stack     at async Promise.all (index 1)
33 verbose stack     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:134:5)
33 verbose stack     at async Install.install (/usr/local/lib/node_modules/npm/lib/install.js:137:5)
34 verbose cwd /
35 verbose Linux 5.4.0-72-generic
36 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "sonarqube-scanner"
37 verbose node v15.14.0
38 verbose npm  v7.10.0
39 error Tracker "idealTree" already exists
40 verbose exit 1

**Comment by gabssnake** [comment]
Hey @gabricar, did you manage to get this working? Is this related to the Alpine issue other's have had?

**Comment by gabssnake** [comment]
Closing this as stale. Feel free to reopen in new information comes up.
