### ISSUE TITLE
Problem to access the link of Docker manual installation on Readme.MD

### ISSUE THREAD

**Issue by mendesbarreto** [bellingard/sonar-scanner-npm#123]
Hello guys,

I am trying to run this package on docker, but I am having trouble with his message: .../jre/bin/java: not found. 

So while I was reading the docs I saw this step:
![Screen Shot 2021-05-03 at 5 28 48 PM](https://user-images.githubusercontent.com/2684784/116935938-188bee80-ac35-11eb-9dcf-7b7affee1d86.png)

But the link is not working, someone can help me?

Thx

**Comment by gabssnake** [comment]
Hey @mendesbarreto did you find a newer link for this?
