### ISSUE TITLE
Scan only the files which are required

### ISSUE THREAD

**Issue by vai995** [bellingard/sonar-scanner-npm#135]
Hi Team,

We are trying to run sonar only on the staged files when we are about to commit the files to the git repo. Couldn't find a solution, if there is anything that we missed to study about the library, can you please redirect us to the right path?

Thank you,
-Vaibhav

**Comment by gabssnake** [comment]
Hi @vai995 did you find your way around this?

**Comment by gabssnake** [comment]
Closing this as stale. Feel free to reopen if there something new to add.
