### ISSUE TITLE
Moderate Vulnerability in sonarqube-scanner > download > got 

### ISSUE THREAD

**Issue by dtomasbar** [bellingard/sonar-scanner-npm#140]
While installing _sonarqube-scanner_ npm reveled the following vulnerability:

> Moderate: Got allows a redirect to a UNIX socket
> Package: got
> Patched in: >=11.8.5
> Dependency of: sonarqube-scanner [dev]
> Path: sonarqube-scanner > download > got
> More info: https://github.com/advisories/GHSA-pfrx-2q88-qq97

Reviewing _download_ issues they haven't yet patched their package, but already have and [open issue](https://github.com/kevva/download/issues/224).

However, _sonnarqube-scanner_ is not using the latest version of _download_ library (v8.0.0) so it may be worth it to check compatibility with the current version of _downalod_ to ensure that there are no issues

**Comment by Ixtalo** [comment]
+1 confirm

**Comment by ZergRushJoe** [comment]
+1

**Comment by wbt** [comment]
The latest version of the download package doesn't have this fixed, which (for future reference of commenters above) you can verify by checking its package.json.

The open issue to do that is [here](https://github.com/kevva/download/issues/224), but likely won't be acted on with that package [lacking any active maintainers](https://github.com/kevva/bin-wrapper/issues/79).

If Sonar has funding for its offerings, I'd recommend picking from this list: 

1. Funding the maintainer of the dependency
2. Taking over management of the dependency via a fork
3. Replacing the dependency with a different one

Having a persistent transitive vulnerability in a product aimed at organizations who are especially picky about eliminating potential issues from their code base is not a good look.

**Comment by cami-dev** [comment]
+1 we have the same issues on all our apps +10

**Comment by drodil** [comment]
+1

**Comment by tokra** [comment]
New library 2.8.2 is not causing this see my comment: https://github.com/bellingard/sonar-scanner-npm/pull/144#issuecomment-1257742264

**Comment by gabssnake** [comment]
This was fixed with 2.8.2 release, see:
https://github.com/bellingard/sonar-scanner-npm/releases/tag/2.8.2
