### ISSUE TITLE
customScanner broken / calls own shell script `sonar-scanner`

### ISSUE THREAD

**Issue by robaca** [bellingard/sonar-scanner-npm#141]
Hi,

we just have the issue, that we try to use the customScanner export, as we get another error when downloading the scanner via the library. Now we found out, that the `getLocalSonarScannerExecutable()` calls the own binary script from `<module-root>/bin/sonar-scanner` instead of calling the correct binary from the path.

As it's currently not possible to define a custom path explicitly, the customScanner functionality seems to be broken completely.

Best regards,
Carsten

**Comment by gabssnake** [comment]
Hey @robaca can you confirm this is still an a problem? Have you found a workaround?

**Comment by robaca** [comment]
Hi @gabssnake we worked around the problem via
```
sed -i -e "s|var command = 'sonar-scanner'|var command = '/opt/sonar-scanner/bin/sonar-scanner'|g" node_modules/sonarqube-scanner/dist/sonar-scanner-executable.js
```

**Comment by gabssnake** [comment]
Thanks for the feedback! Do you want to try a PR?

**Comment by romanbalayan** [comment]
Hi @robaca, @gabssnake,

If I understand correctly, the customScanner should work? Although not explicit on the README, should work if the local installation of `sonar-scanner` is defined in environment `$PATH` variable.

Maybe the use case can be clarified on the sample usage documentation.

**Comment by romanbalayan** [comment]
Hi @gabssnake ,

Created PR : #157  for this.

Also full disclosure, doing this as part of Hacktoberfest 2022. 

Thanks.

**Comment by gabssnake** [comment]
Hi @romanbalayan, that makes sense. Also I think depending on the environment, it might be tricky to set.

@robaca can you confirm that @romanbalayan suggestion works in your case?

**Comment by romanbalayan** [comment]
Hi @gabssnake,

I agree that the specific step on _how_ to set the environment variable is tricky (as this heavily depends on the system where the application will be running, etc) - but I guess its important to explicitly specify that it _should_ be set.
