### ISSUE TITLE
Java Runtime Environment Crashes Analysis

### ISSUE THREAD

**Issue by gabsmprocha** [bellingard/sonar-scanner-npm#145]
Hi guys, has anyone run into this problem?

<img width="1292" alt="Captura de Tela 2022-08-17 às 01 00 11" src="https://user-images.githubusercontent.com/90699433/185032589-d49aade2-d7c3-43cd-bad3-c0b4f6d263a1.png">

**Comment by gabssnake** [comment]
Hi @gabsmprocha (cool name!), is this still an issue for you?

**Comment by gabssnake** [comment]
Closing this as stale. Feel free to reopen if new information comes up.
