### ISSUE TITLE
Clean up temp folder when new version of the Scanner CLI has been installed

### ISSUE THREAD

**Issue by bellingard** [bellingard/sonar-scanner-npm#15]
Otherwise this temp folder will grow infinitely

**Comment by gabssnake** [comment]
Can you confirm this is still an issue?

**Comment by gabssnake** [comment]
I created a list of potential improvements (and issues) and mentioned this topic:
* #165

I'll close this issue for now. Feel free to reopen if you want to create a PR ;)
