### ISSUE TITLE
2.8.2 can't download via proxy

### ISSUE THREAD

**Issue by asselin** [bellingard/sonar-scanner-npm#152]
With version 2.8.1, the scanner download code allows you to set the `https_proxy` / `http_proxy` env vars to specify a proxy to use to download.  Version 2.8.2 does not respect those env vars for proxy downloads.

I assume this is probably due to the switch from the `download` module in 2.8.1 to `node-downloader-helper` in 2.8.2.

Example script that works with 2.8.1 but fails with 2.8.2:
```sh
export https_proxy=<myproxy>
export http_proxy=<myproxy>
npm install -g sonarqube-scanner
sonar-scanner -v
```

Can we please get support for proxies restored in the downloader?

**Comment by gabssnake** [comment]
Hi @asselin, unfortunately this was a feature of the `download` module, not an explicit feature of this package.

Would you be able to use the `SONAR_SCANNER_MIRROR`environment variable described in the README?

Otherwise, would you like to try a PR?

**Comment by csturiale** [comment]
added a [PR](https://github.com/bellingard/sonar-scanner-npm/pull/153)

**Comment by gabssnake** [comment]
See https://github.com/bellingard/sonar-scanner-npm/pull/154

**Comment by dve** [comment]
Sorry to bother you, but do you have a plan when to release this fix? I guess some projects have the same problem like ours - from within the ci only traffic via the proxy is allowed to go outside.
Else we would implement a hack with a pre-dowloaded file.
