### ISSUE TITLE
v2.8.2 breaks bitbucket pipelines build

### ISSUE THREAD

**Issue by oliviernt** [bellingard/sonar-scanner-npm#158]
Hi,

v2.8.2 breaks our sonar scans on Bitbucket Pipelines with the following error:

```[14:08:30] Starting analysis...
[14:08:31] Getting info from "package.json" file
[14:08:31] Checking if executable exists: /build/path/.sonar/native-sonar-scanner/sonar-scanner-4.5.0.2216-linux/bin/sonar-scanner
[14:08:31] Could not find executable in "/build/path/.sonar/native-sonar-scanner".
[14:08:31] Proceed with download of the platform binaries for SonarScanner...
[14:08:31] Creating /build/path/.sonar/native-sonar-scanner
[14:08:31] Downloading from https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.5.0.2216-linux.zip
[14:08:31] (executable will be saved in cache folder: /build/path/.sonar/native-sonar-scanner)
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run sonar stderr:
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^
[Error: EEXIST: file already exists, symlink '../java.base/ASSEMBLY_EXCEPTION' -> '/build/path/.sonar/native-sonar-scanner/sonar-scanner-4.5.0.2216-linux/jre/legal/jdk.jfr/ASSEMBLY_EXCEPTION'] {
  errno: -17,
  code: 'EEXIST',
  syscall: 'symlink',
  path: '../java.base/ASSEMBLY_EXCEPTION',
  dest: '/build/path/.sonar/native-sonar-scanner/sonar-scanner-4.5.0.2216-linux/jre/legal/jdk.jfr/ASSEMBLY_EXCEPTION'
}
error Command failed with exit code 1.
```

I've tried deleting `/build/path/.sonar` before the build but it doesn't resolve the issue.

**Comment by gabssnake** [comment]
Hi @oliviernt, are you overriding `SONAR_SCANNER_VERSION`?
I would expect to see version 4.7 as per https://github.com/bellingard/sonar-scanner-npm/commit/dc623b37f07350bc3099c107c8c0b08c1fb26934

**Comment by dzienisz** [comment]
@gabssnake can we release another version with my **SONAR_SCANNER_VERSION** update?

**Comment by oliviernt** [comment]
@gabssnake not that I would be aware of.

**Comment by oliviernt** [comment]
I double checked and can affirm we're not setting the version explicitly.

**Comment by gabriel-vivas-sonarsource** [comment]
There is a new version released, let me know if you are still having this issue.

**Comment by gabriel-vivas-sonarsource** [comment]
There is a new version released, let me know if you are still having this issue.

**Comment by gabssnake** [comment]
There is a new version released, let me know if you are still having this issue.

**Comment by gabssnake** [comment]
Hi @oliviernt,

I created a list of potential improvements and mentioned the problem you are/were experiencing:
* #165

I'll close this issue for now. Feel free to reopen if you have for information.

**Comment by oliviernt** [comment]
Hey @gabssnake 

Thanks a lot. v2.9.1 works for us!

Cheers!
