### ISSUE TITLE
Allow users to use scanner asynchronously

### ISSUE THREAD

**Issue by Leonelmarianog** [bellingard/sonar-scanner-npm#161]
Hello,

I have an use case where I don't need to wait for an analysis to finish before doing something else. Since the scanner expects a callback, I thought doing something like this would suffice, however, it does not, it completely blocks my code.

```javascript
// scanner.js
import * as scanner from 'sonarqube-scanner';

export const scan = async (options) => {
   return new Promise((resolve) => scanner(options, resolve));
}

// main.js
import { scan } from 'scanner.js';

const init = () => {
   const scanningOptions = { ... };
   
   scan(scanningOptions); // I don't wait for this to finish
   
   // do something else
}
```

I noticed the module uses `execFileSync` when executing the scanner...

![image](https://user-images.githubusercontent.com/60404954/201432785-4e45cb99-4a19-493b-a1b0-9a91e5f2533a.png)

If I change that by the asynchronous version of the same function...

![image](https://user-images.githubusercontent.com/60404954/201433197-cfd435e2-970e-4e37-a25a-8e7f7238d7bc.png)

![image](https://user-images.githubusercontent.com/60404954/201433297-a85c9999-6c05-480d-ad64-ee83681bbce6.png)

...it seems to fix my issue.

- Would this cause any side-effects when running the scanner?
- Is there a reason as to why we are using the synchronous version of `execFile`? 

Thanks.

**Comment by gabssnake** [comment]
Hi @Leonelmarianog, thanks for looking into this.
I don't think there is any particular need to do this synchronously, so your suggestion would be welcome.
Do you want to try a PR with this change?

**Comment by Leonelmarianog** [comment]
@gabssnake I would love to, but changing `execFileSync` for `execFile` makes all the logging information from the `scannerExecutable` dissapear which doesn't break the scanner, but may be a desired feature. I would need a bit of free time to take a look into that.

In the meantime, I will update the title of this issue as a request. 

Thanks for the response.

**Comment by gabssnake** [comment]
Hi @Leonelmarianog,

I created a list of potential improvements and mentioned this improvement:
* #165

I'll close this issue for now. Feel free to reopen if you come up with something :)

**Comment by Leonelmarianog** [comment]
Thanks @gabssnake !
