### ISSUE TITLE
Fails to download executables

### ISSUE THREAD

**Issue by tstackhouse** [bellingard/sonar-scanner-npm#169]
Using this project, if the binaries don't already exist, we attempt to download them, but the process seems to immediately exit with no error, and the binaries are never downloaded.  If I manually download the binaries it works as expected.

**Comment by bellingard** [comment]
This project is now officially taken care of by SonarSource at https://github.com/SonarSource/sonar-scanner-npm.

Please go there to report the issue. Thanks!
