### ISSUE TITLE
The 2.9.x release is a breaking change on Java 8

### ISSUE THREAD

**Issue by sgarfinkel** [bellingard/sonar-scanner-npm#172]
At least it is on our version of Java 8. I have limited ability to change the Java version on these boxes so ideally it'd be nice if the 2.x.x stream remain compatible with Java 8:
```
bash-4.2$ java -version
java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b26)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b26, mixed mode)
```

On 2.9.x:
```
[17:49:10] Starting analysis...
[17:49:10] Getting info from "package.json" file
[17:49:10] Checking if executable exists: /home/jenkins/.sonar/native-sonar-scanner/sonar-scanner-4.7.0.2747-linux/bin/sonar-scanner
[17:49:10] Platform binaries for SonarScanner found. Using it.
Error occurred during initialization of VM
java/lang/NoClassDefFoundError: java/lang/Object
```

We accidentally picked up 2.9.x because of a pinned version, but given this is actually a breaking change, can this PR (https://github.com/bellingard/sonar-scanner-npm/pull/151) please be reverted, a patch version released to resolve this problem for downstream users, then a major release prepared with this change brought back in?

**Comment by bellingard** [comment]
This project is now officially taken care of by SonarSource at https://github.com/SonarSource/sonar-scanner-npm.

Please go there to report the issue. Thanks!
