### ISSUE TITLE
Publish 2.1.0 on NPM repo

### ISSUE THREAD

**Issue by gustavodegeus** [bellingard/sonar-scanner-npm#31]
Hi there,
Thanks a lot for this wrapper, its very handy! 👍 

Could you please publish the latests version on NPM?
I'd like to use the mirror feature and its not available in the version available on NPM now (2.0.1).

Thanks! :)

**Comment by bellingard** [comment]
Hi @gustavodegeus 
I've released version 2.0.2 that offers the mirroring feature.
Enjoy!
