### ISSUE TITLE
avoid gulp-util

### ISSUE THREAD

**Issue by davidkarlsen** [bellingard/sonar-scanner-npm#34]
```
warning sonarqube-scanner > download > gulp-decompress > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
```
See https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

**Comment by hypomn** [comment]
I htink, the dependency to [download ](https://www.npmjs.com/package/download) should be upgraded from 4.4.3 to 7.0.0 in order to resolve this issue.

**Comment by bellingard** [comment]
Gulp was removed.
