### ISSUE TITLE
Pass project key/name and version via the command line args rather than read from package.json 

### ISSUE THREAD

**Issue by atecey** [bellingard/sonar-scanner-npm#37]
Is it possible to pass project key/name and version via the command line args rather than read from package.json?

**Comment by bellingard** [comment]
Yes, this is possible. For instance:

`sonar-scanner -Dsonar.projectKey=my-project-key -Dsonar.projectName=MyProject -Dsonar.projectVersion=1.0.0 -Dsonar.sources=src`
