### ISSUE TITLE
node-slug has regular expression denial of service

### ISSUE THREAD

**Issue by raksit31667** [bellingard/sonar-scanner-npm#44]
Hi, @bellingard 

I found that when I installed this package, npm warned me about security of `slug` dependency.

> npm WARN notice [SECURITY] slug has the following vulnerability: 1. moderate, Go here for more details: https://nodesecurity.io/advisories/537 ...

Then, I cannot deploy my application due to quarantine error.

So, is there anyway to use some alternatives of `slug` ?

Thanks

**Comment by bellingard** [comment]
I don't know if there is an alternative, and to be honest, the user inputs that ```slug``` uses are configuration elements that the developers specify -  so the risque of Regexp DoS is really unlikely.

**Comment by atgjack** [comment]
@bellingard it looks like the attached PR should fix this issue. Can you merge this?

**Comment by bellingard** [comment]
And this is merged!
