### ISSUE TITLE
Exit with sonar-scanner exit code

### ISSUE THREAD

**Issue by wisaac407** [bellingard/sonar-scanner-npm#46]
There is no way of knowing if sonar-scanner succeeded or not. That means that the Build Breaker plugin can't be used.

**Comment by lazytesting** [comment]
Would be great to have this, as it allows us to use this plugin in our CI pipeline.

**Comment by agasser** [comment]
Please take a look at @wisaac407 's PR. It does seem to be onto something. The Build Breaker error is being misinterpreted as a download failure, and the error is being eaten after logging it (the process return code is 0).

**Comment by agasser** [comment]
In the meantime, a workaround is to download the scanner before executing the scan. A script like this does the trick:
```
#!/usr/bin/env node
var sonarQubeExecutable =
    require('../node_modules/sonarqube-scanner/dist/sonarqube-scanner-executable').getSonarQubeScannerExecutable

sonarQubeExecutable(sonarCommand => {
  console.log('Sonar executable path: ' + sonarCommand)
})
```

Another possible alternative would be to use the custom scanner, but I haven't tried that.

**Comment by gwcoffey** [comment]
As a workaround for command line usage, it works for me to simply request the help first:

    ./node_modules/.bin/sonar-scanner --help && ./node_modules/.bin/sonar-scanner

**Comment by bellingard** [comment]
Fixed.
