### ISSUE TITLE
Validation of project reactor failed for scoped module

### ISSUE THREAD

**Issue by agirorn** [bellingard/sonar-scanner-npm#48]
This bug was introduced in sonar-scanner-npm@2.1.0 it works in 2.0.2 and 2.1.0

the scanner running an analysis on a scoped module removed the '/' from the module key/name should be "@scope/module-name" but is "@scopemodule-name" and then it complains this is not a valid project or module key.  

```
ERROR: Error during SonarQube Scanner execution
ERROR: Validation of project reactor failed:
  o "@scope/module-name" is not a valid project or module key. Allowed characters are alphanumeric, '-', '_', '.' and ':', with at least one non-digit.
ERROR: 
ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.
child_process.js:624
    throw err;
    ^
```

**Comment by bellingard** [comment]
Hi, I guess you mean that it was introduced in version 2.1.1, right?

Can you please give a reproducer? (a GitHub repo would be perfect)

**Comment by agirorn** [comment]
I don't have an open source repo that has this issue, I only have it occurring in our private repos/modules. But you could essentially do it with any module, just change its name from "module-name" to "@scope/module-name" and you will get this error.

**Comment by Bangsadrengur** [comment]
This may originate from replacing [slug](https://www.npmjs.com/package/slug) with [slugify](https://www.npmjs.com/package/slugify) in commit https://github.com/bellingard/sonar-scanner-npm/commit/1a44c4ce13705b795e7a7442c46739f2b68f9be5

Testing string '@my/module' shows different output between the two modules
```
$ node
> const slugify = require('slugify');
undefined
> const slug = require('slug');
undefined
> slugify('@my/module');
'@mymodule'
> slug('@my/module');
'mymodule'
$ node --version
v8.11.3
$ npm --version
6.4.1
$ tail -n2 node_modules/slug/package.json | head -n1
  "version": "0.9.1"
$ tail -n2 node_modules/slugify/package.json | head -n1
  "version": "1.3.1"
```

**Comment by samaxes** [comment]
I'm hitting the same issue.
When can we expect a fix for it?

**Comment by bellingard** [comment]
Fixed. Release will happen in a minute.
