### ISSUE TITLE
ENV for something like SONARQUBE_SCANNER_HOME

### ISSUE THREAD

**Issue by imcotton** [bellingard/sonar-scanner-npm#56]
https://github.com/bellingard/sonar-scanner-npm/blob/e65aa4cb2b693511fb0829ff2d64bf1306bd032c/dist/sonarqube-scanner-executable.js#L61

Currently the install location is set to `$HOME`, would be great to set manually in order to play well in container based CI system, for caching mostly.

```javascript
process.env.SONARQUBE_SCANNER_HOME || os.homedir()
```

**Comment by gabssnake** [comment]
Hey @imcotton, do you still care about this?

**Comment by gabssnake** [comment]
Hi @imcotton,

I created a list of potential improvements and mentioned this topic:
* #165

I'll close this issue for now. Feel free to reopen if you want to create a PR ;)
