### ISSUE TITLE
Show result in console

### ISSUE THREAD

**Issue by KayHS** [bellingard/sonar-scanner-npm#62]
Hi,

I have docker image that runs sonar and i use sonarqube to analyze my typescript project.

I would like to use this in my CI Pipeline is there a way to show some summary report in the console?

```
const sonarqubeScanner = require('sonarqube-scanner');
sonarqubeScanner({
    serverUrl: 'http://localhost:9999',
    options: {
        'sonar.sources': '.',
        'sonar.inclusions': 'src/**' // Entry point of your code
    }
}, () => {});
```

Btw why do i get 0.0% coverage is this to do with tests?

**Comment by bellingard** [comment]
The scanner just triggers the analysis, which produces a report that is sent to the SonarQube server for asynchronous processing. So you cannot show results in the console.

**Comment by KayHS** [comment]
Okay thank you.

So there is no way of being able to use this for example in my CI pipeline to show the result and exit if it fails.

**Comment by DanielRuf** [comment]
Same issue here. I could need this.

> Okay thank you.
> 
> So there is no way of being able to use this for example in my CI pipeline to show the result and exit if it fails.
