### ISSUE TITLE
Failed to parse JSON in SONARQUBE_SCANNER_PARAMS environment variable 

### ISSUE THREAD

**Issue by danilovaz** [bellingard/sonar-scanner-npm#7]
I'm trying to run the Sonar task using **customScanner**. However, when I run the task it returns the following error: Failed to parse JSON in SONARQUBE_SCANNER_PARAMS environment variable.

I want to know if this is the correct setting when I want to run with the Local Sonar-Scanner:
```js
const gulp = require('gulp');
const sonarqubeScanner = require('sonarqube-scanner').customScanner;
const conf = require('../conf/gulp.conf');

gulp.task('sonar', sonar);

function sonar(callback) {
  sonarqubeScanner({
    serverUrl : "https://mysonar.url.com.br/",
     options : {
      projectKey: 'myProject:name',
      projectName: 'name',
      projectVersion: '1.0.0.0',
      sources: 'src',
      language: 'js',
      sourceEncoding: 'UTF-8',
      exclusions:".tmp/**, dist/**, node_modules/**, bower_components/**",
      javascript: {
        lcov: {
          reportPath: 'results/lcov.info'
        }
      }
    }
  }, callback);
}

```

The only environment variable I set was the Sonar path: **/opt/sonar-runner/bin**. And I also created the **sonar-project.properties** file inside my directory project but the task never seems to get this file. I ran Sonar straight (without the task): **sonar-scanner** and it worked perfectly, but with the package it never works.

I did a lot of testing and I did not come up with a solution. Could you tell me what it could be? Thanks, so much!

**Comment by bellingard** [comment]
When using the `sonarqube-scanner` package (custom or not), the `sonar-project.properties` is ignored. The package uses:
1. Information found in your `package.json` file - if you have one
    - For instance the version or the project name
2. Information specified in the `options` parameter - to complement what might have been found in the `package.json` file
    - For instance you can indeed set some exclusions

I think that the error you get is due to the way you specify the `options` parameters. You are writing them in a "JSON" way whereas for the moment, it expects the options to be written in "properties" way. In your example, this would be:

```
function sonar(callback) {
  sonarqubeScanner({
    serverUrl : "https://mysonar.url.com.br/",
     options : {
      "sonar.projectKey": 'myProject:name',
      "sonar.projectName": 'name',
      "sonar.projectVersion": '1.0.0.0',
      "sonar.sources": 'src',
      "sonar.language": 'js',
      "sonar.sourceEncoding": 'UTF-8',
      "sonar.exclusions:".tmp/**, dist/**, node_modules/**, bower_components/**",
      "sonar.javascript.lcov.reportPath": 'results/lcov.info'
    }
  }, callback);
}
```
Tell me if that works!

**Comment by danilovaz** [comment]
@bellingard  Thank you. Worked perfectly. The team is very happy with the package, it's easy to use it to configure Sonar :beers:
