### ISSUE TITLE
Error during SonarQube Scanner execution java.lang.IllegalStateException:     Unable to register extension fr.cnes.sonar.plugins.icode.check.ICodeSensor from plugin 'icode'

### ISSUE THREAD

**Issue by rmcroft** [bellingard/sonar-scanner-npm#72]
We are using SonarQube version 7.7 and when we try to use the 2.5 version of the sonar-scanner it throws this error in the logs:

"Error during SonarQube Scanner execution java.lang.IllegalStateException:
    Unable to register extension fr.cnes.sonar.plugins.icode.check.ICodeSensor from plugin 'icode'"

If we go back to version 2.4 it works properly.

**Comment by gabssnake** [comment]
Hi @rmcroft, is this still an issue for you in the latest version?
