### ISSUE TITLE
Clarity about binary name

### ISSUE THREAD

**Issue by DanielRuf** [bellingard/sonar-scanner-npm#73]
I have already `sonar-scanner` in my PATH so the binary name conflicts with this. Shouldn't it be `sonarqube-scanner` or is it meant as dropin replacement?

**Comment by bellingard** [comment]
It is meant to be a replacement, so that your CI scripts work exactly the same way as what you're used to doing locally with a "manual" installation.

**Comment by bellingard** [comment]
Ideally, the name of the npm package should have been "sonar-scanner", but it was already taken (https://www.npmjs.com/package/sonar-scanner).
