### ISSUE TITLE
Add option to disable OS check

### ISSUE THREAD

**Issue by rkullas** [bellingard/sonar-scanner-npm#74]
You check in your scripts on which OS the sonarqube-scanner will be executed and you download the corresponding zip file with the scanner jar. The zip also contains a java version which is always used to start the scanner. The problem in my environment is that our Sonar server is running with SSL with a self signed certificate which leads to an error with the java version included in the zip. On the mirror where you download the archive a zip file also exists without an OS name which does not include a jre and uses the jre/jdk on the host system. 

I need a flag or config possibility to use and download the archive which does not contain a jre.

**Comment by gabssnake** [comment]
Hey @rkullas, is this still an issue for you?

**Comment by gabssnake** [comment]
Hi @rkullas,

I created a list of potential improvements and mentioned this topic:
* #165

I'll close this issue for now. Feel free to reopen if you want to create a PR ;)
