### ISSUE TITLE
Cache folder problem on Windows

### ISSUE THREAD

**Issue by rschellius** [bellingard/sonar-scanner-npm#8]
Hi,

I'd like to use the sonar-scanner via a gulpfile to scan my nodejs project. I get an error when the scanner tries to use the downloaded Windows zip in my user directory, because the name of that  folder contains a space.  

`(executable will be saved in cache folder: C:\Users\My Name\.sonar\native-sonar-scanner)`

The error:

`'C:\Users\My' is not recognized as an internal or external command'`

I've tried to change the default .sonar cache folder in the options json, but that doesn't seem to work. My options:

    sonarqubeScanner({
        serverUrl: "https://sonarqube.com",
        options: {
            "sonar.projectName": "Node Project",
            "sonar.working.directory": "./.sonar",
            "sonar.sources": ".",
            "sonar.verbose": "true"
        }
    }, callback);

This doesn't solve it. Any help? Thanks in advance.

**Comment by bellingard** [comment]
Looks like that's a known issue with `child_process#exec()`. And seems like `child_process#execFile()` solves the problem.

Would you do a quick test for me please?
In your project,  open `node_modules/sonarqube-scanner/dist/index.js` and replace:
* On line # 1 => `execSync` by `execFileSync`
* On line # 26 => `exec(sqScannerCommand, options_exec);` by `exec(sqScannerCommand, [], options_exec);`

**Comment by rschellius** [comment]
Yes, that solved it.

**Comment by bellingard** [comment]
Thanks @rschellius for the test, I will fix and do a release.

**Comment by bellingard** [comment]
There are regressions. Need to find out why.

**Comment by bellingard** [comment]
OK, everything was good in fact. I'm going to release.
