### ISSUE TITLE
Upgrade embedded sonar-scanner-cli to latest

### ISSUE THREAD

**Issue by narwajea** [bellingard/sonar-scanner-npm#80]
Version 4.2.0.1873 is available in https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/.

Is it possible to upgrade sonar-scanner-npm with this new version?

**Comment by esskar** [comment]
Agreed. I filled a pull-request so that the version can be passed as a parameter. See #81 for more information.

**Comment by narwajea** [comment]
4.3.0.2102 has been released in the meantime.

**Comment by bellingard** [comment]
Fixed.
