### ISSUE TITLE
Path to config?

### ISSUE THREAD

**Issue by basickarl** [bellingard/sonar-scanner-npm#87]
Hi! I'm wondering there is a way to set where the config file lies, I have all my configs which aren't in source control in a directory called "config", anyway to make it look there? Alternatively make the sonar-scanner command recursively look for the first config file.

**Comment by 0m4r** [comment]
I think all that needs to be done to enable this is to modify the **dist/index.js** file like this:

```js
/*
 * Function used programmatically to trigger an analysis.
 */
function scan(params, callback, args = []) {
  scanCLI(args, params, callback)
}
```

and then you would need to use it like:
```js
sonarQubeScanner(
  {}, 
  () => setTimeout(callback, 2000), 
  [`-Dproject.settings=path/to/my/config/file.properties`]
);
```

I could make a PR if @bellingard considers this a viable option.
I would also need to have this configurable and I'd like not to fork this but rather continue using it and if possible contribute to it ;)

**Comment by gabssnake** [comment]
Hey folks, still interested in a PR?

**Comment by gabssnake** [comment]
Hi @basickarl and @0m4r,

Not sure if you still care about this. I created a list of potential improvements and mentioned this topic:
* #165

I'll close this issue for now. Feel free to reopen if you have any feedback.
