### ISSUE TITLE
TypeScript types?

### ISSUE THREAD

**Issue by basickarl** [bellingard/sonar-scanner-npm#88]
TypeScript types? Do they exist for this project?

**Comment by gabssnake** [comment]
Hello @basickarl, they don't exist.
Would you be interested in submitting a PR to add them?

**Comment by gabssnake** [comment]
Hi @basickarl,

Thanks for bringing this up. I added this topic to a list of potential improvments:
* #165

I'll close this issue for now. Feel free to reopen if you want to create a PR ;)
